export const GET_BOOKS = "GET_BOOKS";
export const USER_SIGNUP = "USER_SIGNUP";
export const USER_SIGNIN = "USER_SIGNIN";
export const LOG_OUT = "LOG_OUT";
export const USER_LOGIN_ALERT = "USER_LOGIN_ALERT";
export const SINGLE_BOOK_FETCH = "SINGLE_BOOK_FETCH";
export const EDIT_BOOK_DETAILS = "EDIT_BOOK_DETAILS";
export const POST_NEW_BOOKS = "POST_NEW_BOOKS";
export const SINGLEBOOK_DETAIL_REMOVE = "SINGLEBOOK_DETAIL_REMOVE";
export const BOOK_IMAGE_ID = "BOOK_IMAGE_ID";
export const GET_NFT_REQUEST = "GET_NFT_REQUEST"
export const GET_NFT = "GET_NFT"
export const GET_NFT_FAILED = "GET_NFT_FAILED"

export const GET_PROJECT_REQUEST = "GET_PROJECT_REQUEST"
export const GET_PROJECT = "GET_PROJECT"
export const GET_PROJECT_FAILED = "GET_PROJECT_FAILED"

export const CURRENT_PROJECT = "CURRENT_PROJECT"

export const EDIT_PROJECT_MODAL = "EDIT_PROJECT_MODAL"
